### ISSUE TITLE
Incomplete code

### ISSUE THREAD

**Issue by qzhu2017** [FelipeT94/Schrodinger#3]
@FelipeT94 
Just quickly run the code as follows. This code depends on another file named `Schroedinger.java`
```
qiangzhu@deptanonpool-238:~/Desktop/github/Schrodinger$ javac 1D.java 
1D.java:7: error: class Schroedinger is public, should be declared in a file named Schroedinger.java
public class Schroedinger {
       ^
1 error
```

**Comment by FelipeT94** [comment]
When I compiled the code on https://www.jdoodle.com/online-java-compiler I didn't receive an error code. It produced an output for the eigenvalue. I will look into why the code works with some compilers and not others.

**Comment by qzhu2017** [comment]
The correct way to run java in MacOS
```
qiangzhu@Qiangs-MBP:~/Desktop/github/Schrodinger$ javac Schroedinger.java 
qiangzhu@Qiangs-MBP:~/Desktop/github/Schrodinger$ java Schroedinger
The eigenvalue: 2.499999201266505
```

**Comment by FelipeT94** [comment]
I was not able to finish the code due to moving apartments during the week. I will continue to work on it and try to have it complete by the end of Saturday.
